/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/core/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 헬스체크
         * @description 서비스의 상태를 확인합니다.
         *
         *         **사용 사례:**
         *         - 로드밸런서의 헬스체크 타겟
         *         - 모니터링 툴 (Datadog, New Relic 등)
         *         - Kubernetes Liveness Probe
         *
         *         **응답 상태:**
         *         - `ok`: 정상 작동
         *         - `degraded`: 일부 기능 제한 (예: DB 연결 불안정)
         *         - `error`: 서비스 이용 불가
         */
        get: operations["health_check_core_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/core/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 버전 정보
         * @description 애플리케이션의 버전 정보를 반환합니다.
         *
         *         **사용 사례:**
         *         - 배포 후 버전 확인
         *         - 프론트엔드에서 API 버전 체크
         *         - 디버깅 시 환경 확인
         *
         *         **활용 예시:**
         *         ```bash
         *         # 배포 확인
         *         curl https://api.example.com/core/version
         *
         *         # 프론트엔드에서 버전 불일치 감지
         *         if (apiVersion !== expectedVersion) {
         *           alert('새 버전이 배포되었습니다. 페이지를 새로고침해주세요.');
         *         }
         *         ```
         */
        get: operations["version_info_core_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sample/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 샘플 데이터 목록 조회
         * @description 전체 샘플 데이터 목록을 반환합니다.
         */
        get: operations["list_sample_api_v1_sample__get"];
        put?: never;
        /**
         * 샘플 데이터 생성
         * @description 새로운 샘플 데이터를 생성합니다.
         */
        post: operations["create_sample_api_v1_sample__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sample/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 샘플 데이터 단건 조회
         * @description ID로 샘플 데이터를 조회합니다.
         */
        get: operations["get_sample_api_v1_sample__item_id__get"];
        /**
         * 샘플 데이터 수정
         * @description 기존 샘플 데이터를 수정합니다.
         */
        put: operations["update_sample_api_v1_sample__item_id__put"];
        post?: never;
        /**
         * 샘플 데이터 삭제
         * @description 샘플 데이터를 삭제합니다.
         */
        delete: operations["delete_sample_api_v1_sample__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/docs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 문서 파일 조회
         * @description 프로젝트 문서 파일(Markdown)을 조회합니다.
         */
        get: operations["get_document_api_v1_docs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/docs/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 문서 목록 조회
         * @description 사용 가능한 문서 목록을 조회합니다.
         */
        get: operations["list_documents_api_v1_docs_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/db-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 데이터베이스 연결 테스트
         * @description Supabase 데이터베이스 연결 상태를 확인하고 테스트 메시지를 반환합니다.
         */
        get: operations["check_database_connection_api_v1_system_db_check_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API 헬스체크
         * @description API v1의 전체 상태를 확인합니다.
         */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 루트 엔드포인트
         * @description 루트 엔드포인트
         *
         *     API 기본 정보를 반환합니다.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiResponse[SampleDataResponse] */
        ApiResponse_SampleDataResponse_: {
            /**
             * Success
             * @description 요청 성공 여부
             */
            success: boolean;
            /** @description 응답 데이터 */
            data?: components["schemas"]["SampleDataResponse"] | null;
            /**
             * Message
             * @description 성공 메시지
             */
            message?: string | null;
            /**
             * Error
             * @description 에러 메시지
             */
            error?: string | null;
        };
        /** ApiResponse[list[SampleDataResponse]] */
        ApiResponse_list_SampleDataResponse__: {
            /**
             * Success
             * @description 요청 성공 여부
             */
            success: boolean;
            /**
             * Data
             * @description 응답 데이터
             */
            data?: components["schemas"]["SampleDataResponse"][] | null;
            /**
             * Message
             * @description 성공 메시지
             */
            message?: string | null;
            /**
             * Error
             * @description 에러 메시지
             */
            error?: string | null;
        };
        /**
         * DBCheckResponse
         * @description DB 연결 체크 응답
         */
        DBCheckResponse: {
            /**
             * Success
             * @description 연결 성공 여부
             */
            success: boolean;
            /**
             * Message
             * @description 연결 메시지
             */
            message: string;
            /**
             * Timestamp
             * Format: date-time
             * @description 응답 시각
             */
            timestamp: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * SampleDataCreate
         * @description 샘플 데이터 생성 요청 스키마
         * @example {
         *       "description": "2026년 1분기 매출 실적",
         *       "name": "매출 데이터",
         *       "score": 0.85,
         *       "value": 1500000
         *     }
         */
        SampleDataCreate: {
            /**
             * Name
             * @description 데이터 이름 (1~255자)
             */
            name: string;
            /**
             * Description
             * @description 상세 설명
             */
            description?: string | null;
            /**
             * Value
             * @description 수치 값
             */
            value: number;
            /**
             * Score
             * @description 점수 (0.0 ~ 1.0)
             */
            score?: number | null;
        };
        /**
         * SampleDataResponse
         * @description 샘플 데이터 응답 스키마
         * @example {
         *       "created_at": "2026-03-26T09:00:00+09:00",
         *       "description": "2026년 1분기 매출 실적",
         *       "id": 1,
         *       "name": "매출 데이터",
         *       "score": 0.85,
         *       "updated_at": "2026-03-26T09:00:00+09:00",
         *       "value": 1500000
         *     }
         */
        SampleDataResponse: {
            /**
             * Id
             * @description 고유 식별자
             */
            id: number;
            /**
             * Name
             * @description 데이터 이름
             */
            name: string;
            /**
             * Description
             * @description 상세 설명
             */
            description?: string | null;
            /**
             * Value
             * @description 수치 값
             */
            value: number;
            /**
             * Score
             * @description 점수 (0.0 ~ 1.0)
             */
            score?: number | null;
            /**
             * Created At
             * Format: date-time
             * @description 생성 시각 (ISO 8601)
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description 수정 시각 (ISO 8601)
             */
            updated_at: string;
        };
        /**
         * SampleDataUpdate
         * @description 샘플 데이터 수정 요청 스키마 (부분 수정 가능)
         * @example {
         *       "name": "수정된 매출 데이터",
         *       "value": 1800000
         *     }
         */
        SampleDataUpdate: {
            /**
             * Name
             * @description 데이터 이름 (1~255자)
             */
            name?: string | null;
            /**
             * Description
             * @description 상세 설명
             */
            description?: string | null;
            /**
             * Value
             * @description 수치 값
             */
            value?: number | null;
            /**
             * Score
             * @description 점수 (0.0 ~ 1.0)
             */
            score?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_core_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    version_info_core_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_sample_api_v1_sample__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_SampleDataResponse__"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_sample_api_v1_sample__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SampleDataCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_SampleDataResponse_"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_sample_api_v1_sample__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_SampleDataResponse_"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_sample_api_v1_sample__item_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SampleDataUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_SampleDataResponse_"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_sample_api_v1_sample__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_document_api_v1_docs_get: {
        parameters: {
            query: {
                /** @description 문서 파일 경로 (예: /ARCHITECTURE.md) */
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_docs_list_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown[];
                    };
                };
            };
        };
    };
    check_database_connection_api_v1_system_db_check_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DBCheckResponse"];
                };
            };
        };
    };
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
